### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by antmachine** [garth0323/blogastram#2]
Project Requirements
- [x] Upload finished project to github
- [ ] Use latest version of Rails 4
- [x] Use ruby 2.2 or newer (we use 2.3 on our main project)
- [x] Rspec unit tests minimum of 10
- [x] One feature test (rspec/capybara)

**Comment by garthcodes** [comment]
@antmachine I am sure you are aware Rails was not really built for downgrading to earlier versions. I have upgraded many apps, never found a reason to downgrade. I did use the latest stable version of Rails. The only way to satisfy this requirement at this time would be to rebuild it completely. This neither seems necessary or prudent. Sorry. I wish I could do it for you.

**Comment by antmachine** [comment]
The project specs ask for the latest stable version of Rails 4. That may not seem prudent to you, but it is necessary. No worries if you can't get to it!

**Comment by garthcodes** [comment]
The part that I was saying was not prudent was me rebuilding an entire app to an earlier version, as I cannot just change to an earlier version of Rails. I appreciate the requirements and should have done it in Rails 4. But rebuilding it would  be a time consuming affair. I already put hours into the coding challenge. I am not sure what new knowledge you would gain about me doing this.
